version = 0.1

[default.global.parameters]
stack_name = "photo-gallery-dev"
region = "eu-central-1"

[default.validate.parameters]
lint = true

[default.build.parameters]
cached = true
parallel = false

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.local_start_api.parameters]
env_vars = "env.local.json"
docker_network = "photo-gallery_default"

[default.local_invoke.parameters]
env_vars = "env.local.json"
docker_network = "photo-gallery_default"