<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.TestUtilities" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PhotoGallery.Core\PhotoGallery.Core.csproj" />
    <ProjectReference Include="..\..\src\PhotoGallery.Upload\PhotoGallery.Upload.csproj" />
    <ProjectReference Include="..\..\src\PhotoGallery.Processing\PhotoGallery.Processing.csproj" />
    <ProjectReference Include="..\..\src\PhotoGallery.Photos\PhotoGallery.Photos.csproj" />
  </ItemGroup>

</Project>
